name: somos molai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24788
title: somos molai
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061201'
    - '#153102'
    - '#115200'
    - '#2f5367'
    - '#4b756a'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.4737757232505828
  rhythmicContrast: 0
purpose: []
